### ISSUE TITLE
error with Makefile

### ISSUE THREAD

**Issue by babayoussef** [DaveBerkeley/serv_soc#2]
I get this : make: *** No rule to make target `serv.bin', needed by `prog'.  Stop. when I write make all

**Comment by DaveBerkeley** [comment]
Hi. It does seem to be broken. I've not touched this for a few years. I'm not sure why the Makefile is not working. I have had a quick look at it.

However, I relied on an old version of SERV. What I should do is add it as a git submodule with a defined git hash so that it always works.

I'm not sure if I'll have time to fix it, but thanks for bringing it to my attention.

**Comment by babayoussef** [comment]
I noticied that the RTL ( CORE=$(SERV)/rtl ) directory is missing: 
So CPU files are missing too:
# CPU internals
CPU_FILES  = $(CORE)/serv_rf_top.v
CPU_FILES += $(CORE)/serv_rf_ram_if.v
CPU_FILES += $(CORE)/serv_rf_ram.v
CPU_FILES += $(CORE)/serv_rf_if.v
CPU_FILES += $(CORE)/serv_mem_if.v
CPU_FILES += $(CORE)/serv_top.v
CPU_FILES += $(CORE)/serv_state.v
CPU_FILES += $(CORE)/serv_decode.v
CPU_FILES += $(CORE)/serv_bufreg.v
CPU_FILES += $(CORE)/serv_ctrl.v
CPU_FILES += $(CORE)/serv_alu.v
CPU_FILES += $(CORE)/serv_shift.v
CPU_FILES += $(CORE)/serv_csr.v

I dont know if there is other missing files. I read your blog and find the article about serv cpu simple and interesting. If you can share a not broken Makefile, Thanks.

**Comment by DaveBerkeley** [comment]
Please read my previous answer.

**Comment by babayoussef** [comment]
Thanks
